---
title: "COVID19 Interactive Shiny App"
description: |
  Pointer to an interactive Shiny app to play with projection models 
author:
  - name: Ankur Singhal 
    url: https://aksinghal86.github.io/covid19
    affiliation: Empirical Solutions Consulting, LLC
date: "2020-04-18"
slug: aksinghal862020covid19ShinyApp
twitter:
  creator: "@skepticalAnkur"
output:
  distill::distill_article:
    toc: false
    toc_depth: 1
    self_contained: false
---

In the first post, I discussed [semi-quantitative methods] (https://aksinghal86.github.io/covid19/posts/estimating-R-in-US/) using packages like `EpiEstim`, `epitrix`, `incidence` and `distcrete` developed by **RECON** to predict the trajectory of COVID19 in the US by state and by county. In the last two posts, I have discussed more formal quantitative methods like [simple logistic regression] (https://aksinghal86.github.io/covid19/posts/covid19-projections-using-logistic_regression/) and [generalized logistic regression] (https://aksinghal86.github.io/covid19/posts/covid19-projections-using-GRM/) to make forecasts about the potential number of cases and deaths in the US. 

I realized that a post can only take so far and I wanted to create something more interactive where it was possible to look at any county or state within the US and see how the models fit and change over time. So I have done just that!!! Check out the new [fancy shiny app] (aksinghal86.shinyapps.io/covid19) where you can play around with all the models and change parameters to see how they affect the fits and the projections. Give it a second to load though -- shiny servers are a bit slow...

